### ISSUE TITLE
No suport for System.Collections.Immutable v1.2?

### ISSUE THREAD

**Issue by enghch** [splunk/splunk-sdk-csharp-pcl#64]
The nuget package for Splunk.Client lists as a dependency:

System.Collections.Immutable (>= 1.1.37 && < 1.2.0)

The latest .Net Core for UWP (5.2.2) comes with System.Collections.Immutable 1.2 therefore Nuget refuses to install Splunk.Client. Will there be an update that bumps the dependency on Systems.Collections.Immutable to 1.2.0 or higher?

**Comment by agc93** [comment]
I am having the same issue but caused by `Microsoft.NETCore.App (>= 1.1.0)` (i.e. the base .NET Core app library) which depends on >= 1.3.0 of `System.Collections.Immutable`.

This means that despite support `Profile111`, this library is totally unusable in .NET Core apps/projects. Can this dependency be relaxed/updated?

**Comment by shakeelmohamed** [comment]
See comment in #65
